In [1]:
import pandas as pd

In [2]:
series=pd.Series([4,6,7,81,23,45])
print(series)

0     4
1     6
2     7
3    81
4    23
5    45
dtype: int64

In [12]:
df=pd.read_csv("D://ML//top_1000_popular_movies_tmdb.csv//top_1000_popular_movies_tmdb.csv" ,engine="python")

In [14]:
df.head(10)

,Unnamed: 0,id,title,release_date,genres,original_language,vote_average,vote_count,popularity,overview,budget,production_companies,revenue,runtime,tagline
0,0,385687,Fast X,2023-05-17,"['Action', 'Crime', 'Thriller']",English,7.4,1347.0,8363.473,Over many missions and against impossible odds...,340000000.0,"['Universal Pictures', 'Original Film', 'One R...",6.520000e+08,142.0,The end of the road begins.
1,1,603692,John Wick: Chapter 4,2023-03-22,"['Action', 'Thriller', 'Crime']",English,7.9,2896.0,4210.313,"With the price on his head ever increasing, Jo...",90000000.0,"['Thunder Road', '87Eleven', 'Summit Entertain...",4.317692e+08,170.0,"No way back, one way out."
2,2,502356,The Super Mario Bros. Movie,2023-04-05,"['Animation', 'Family', 'Adventure', 'Fantasy'...",English,7.8,4628.0,3394.458,"While working underground to fix a water main,...",100000000.0,"['Universal Pictures', 'Illumination', 'Ninten...",1.308767e+09,92.0,NaN
3,3,569094,Spider-Man: Across the Spider-Verse,2023-05-31,"['Action', 'Adventure', 'Animation', 'Science ...",English,8.8,1160.0,2859.047,"After reuniting with Gwen Stacy, Brooklyn’s fu...",100000000.0,"['Columbia Pictures', 'Sony Pictures Animation...",3.135222e+08,140.0,It's how you wear the mask that matters
4,4,536437,Hypnotic,2023-05-11,"['Mystery', 'Thriller', 'Science Fiction']",English,6.5,154.0,2654.854,A detective becomes entangled in a mystery inv...,70000000.0,"['Studio 8', 'Solstice Productions', 'Ingeniou...",0.000000e+00,94.0,Control is an illusion.
5,5,667538,Transformers: Rise of the Beasts,2023-06-06,"['Action', 'Adventure', 'Science Fiction']",English,7.4,195.0,2453.807,When a new threat capable of destroying the en...,200000000.0,"['Skydance', 'Paramount', 'di Bonaventura Pict...",1.710455e+08,127.0,Unite or fall.
6,6,890771,The Black Demon,2023-04-26,"['Horror', 'Thriller']",English,6.5,151.0,1777.200,Oilman Paul Sturges' idyllic family vacation t...,0.0,"['Mucho Mas Media', 'Silk Mass', 'The Avenue E...",0.000000e+00,100.0,Nature bites back.
7,7,447277,The Little Mermaid,2023-05-18,"['Adventure', 'Family', 'Fantasy', 'Romance']",English,6.2,616.0,1448.640,"The youngest of King Triton’s daughters, and t...",250000000.0,"['Walt Disney Pictures', 'Lucamar Productions'...",4.140000e+08,135.0,"Watch and you'll see, some day I'll be, part o..."
8,8,76600,Avatar: The Way of Water,2022-12-14,"['Science Fiction', 'Adventure', 'Action']",English,7.7,8493.0,1344.884,Set more than a decade after the events of the...,460000000.0,"['20th Century Studios', 'Lightstorm Entertain...",2.320250e+09,192.0,Return to Pandora.
9,9,713704,Evil Dead Rise,2023-04-12,"['Thriller', 'Horror']",English,7.1,1597.0,1285.781,Three siblings find an ancient vinyl that give...,15000000.0,"['New Line Cinema', 'Ghost House Pictures', 'R...",1.415121e+08,96.0,Mommy loves you to death.

In [15]:
df.tail(10)

,Unnamed: 0,id,title,release_date,genres,original_language,vote_average,vote_count,popularity,overview,budget,production_companies,revenue,runtime,tagline
9991,9990,14736,Love & Basketball,2000-04-21,"['Comedy', 'Drama', 'Romance']",English,7.5,383.0,12.306,Monica Wright and Quincy McCall grew up in the...,20000000.0,['40 Acres and a Mule Filmworks'],27728118.0,124.0,All's fair in love and basketball.
9992,9991,563067,Fukushima 50,2020-03-06,"['History', 'Drama', 'Action']",Japanese,6.4,136.0,12.305,Workers at the Fukushima Daiichi facility in J...,0.0,"['Shochiku', 'KADOKAWA']",7494243.0,122.0,"In the darkest hours, courage prevails"
9993,9992,396398,The Meyerowitz Stories (New and Selected),2017-10-13,"['Comedy', 'Drama']",English,6.5,1066.0,12.303,An estranged family gathers together in New Yo...,0.0,"['Gilded Halfwing', 'IAC Films']",0.0,112.0,NaN
9994,9993,329981,Shut In,2016-11-11,"['Drama', 'Thriller']",English,5.3,639.0,12.303,A widowed child psychologist lives in an isola...,10000000.0,"['EuropaCorp', 'Lava Bear Films', 'Transfilm I...",13082071.0,91.0,Some fears can't be shut out.
9995,9994,12720,Suicide Club,2001-10-29,"['Drama', 'Horror', 'Thriller']",Japanese,6.6,411.0,12.302,When 54 high school girls throw themselves in ...,250000.0,['Omega Project'],0.0,99.0,"Well then, goodbye everybody."
9996,9995,33142,Vivah,2006-11-10,"['Romance', 'Drama']",Hindi,6.4,70.0,12.301,"Poonam, a traditionally brought-up young woman...",0.0,['Rajshri Productions'],4000000.0,175.0,Marriage isn't a game...
9997,9996,9442,Dead Men Don't Wear Plaid,1982-05-21,"['Comedy', 'Mystery']",English,6.6,324.0,12.301,Juliet Forrest is convinced that the reported ...,9000000.0,"['Universal Pictures', 'Aspen Film Society']",18196170.0,89.0,Laugh...or I’ll blow your lips off!
9998,9997,28774,Communion,1989-11-10,"['Drama', 'Horror', 'Science Fiction', 'Thrill...",English,5.3,147.0,12.300,A novelist's wife and son see him changed by a...,5000000.0,"['The Picture Property Company', 'Allied Visio...",1919653.0,103.0,The true story of one man's terrifying journey...
9999,9998,11121,Tess,1979-10-06,"['Drama', 'Romance']",English,7.0,283.0,12.300,A strong-willed peasant girl is sent by her fa...,12000000.0,"['Renn Productions', 'Timothy Burrill Producti...",20101247.0,186.0,She was born into a world where they called it...
10000,9999,272692,The Possession of Michael King,2014-08-14,['Horror'],English,6.1,346.0,12.297,The film tells the story of documentary filmma...,0.0,"['Quickfire Films', 'Gold Circle Films']",2405143.0,83.0,"If you invite it in, it will never let you go."

In [16]:
df.isnull().sum()

Unnamed: 0                 0
id                         0
title                      0
release_date              23
genres                     0
original_language          1
vote_average               1
vote_count                 1
popularity                 1
overview                  77
budget                     2
production_companies       2
revenue                    2
runtime                    2
tagline                 2618
dtype: int64

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10001 entries, 0 to 10000
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            10001 non-null  object
 1   id                    10001 non-null  int64
 2   title                 10001 non-null  object
 3   release_date          9978 non-null   object
 4   genres                10001 non-null  object
 5   original_language     10000 non-null  object
 6   vote_average          10000 non-null  float64
 7   vote_count            10000 non-null  float64
 8   popularity            10000 non-null  float64
 9   overview              9924 non-null   object
 10  budget                9999 non-null   float64
 11  production_companies  9999 non-null   object
 12  revenue               9999 non-null   float64
 13  runtime               9999 non-null   float64
 14  tagline               7383 non-null   object
dtypes: float64(6), int64(1), object(8)
memory usage: 1.1+ MB